### ISSUE TITLE
Refactor the word "nuget" from documentation

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/VersionMiner#22]
Search codebase for "nuget" and replace with NuGet where applicable. 

**Acceptance Criteria:**
- [ ] text refactored throughout code base

**Comment by CalvinWilkinson** [comment]
Nothing to implement!!

@kselena I do not know what happened here. I searched the entire code base and nothing shows the incorrect spelling of the word `nuget`.  Closed with no changes.  🥳
